### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications. 오류(toast-ui)

### ISSUE THREAD

**Issue by ljk1782** [Witty-Puppy/FrontEnd#21]
```
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:223700:58)
    at http://localhost:3000/static/js/bundle.js:223719:7
```

위와같은 오류가 발생한 상황이다. 버그가 발생한 코드는 다음과 같다.

```jsx
<div className={styles.post_editor_wrap}>
    {/* <button onClick={commentHandler}>보내기</button> */}
    <Editor
        previewStyle='tab'
        initialEditType='markdown'
        toolbarItems={[
            ['heading', 'bold', 'italic', 'strike'],
            ['hr', 'quote'],
            ['ul', 'ol', 'task', 'indent', 'outdent'],
            ['table', 'image', 'link'],
            ['code', 'codeblock'],
        ]}
        ref={editorRef}
        plugins={[chartPlugin, codeSyntaxHighlightPlugin, colorPlugin, tableMergedCellPlugin, umlPlugin]}
        placeholder='게시글을 입력하세요.'
        initialValue={editorText}
        // usageStatistics={false}
        onChange={changeEditorHandler}
    />
</div>
```

**Comment by ljk1782** [comment]
[힌트를 얻은 url](https://velog.io/@yhkim3116/ResizeObserver-loop-completed-with-undelivered-notifications.-%EC%97%90%EB%9F%AC)

해당 글에서 얻은 정보는 chart 라는 것이었다. 

```jsx
plugins={[
    chartPlugin,
    codeSyntaxHighlightPlugin,
    // colorPlugin,
    tableMergedCellPlugin,
    umlPlugin
]}
```

5개의 플러그인 중에 colorPlugin일 경우에만 무한루프에 빠져서 그 경우에는 잘 작동했다. 하지만 나머지 플러그인도 오류가 발생할 수 있기 때문에 우선적으로 열어둔다,
